#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'

require_relative 'lexer'

module Lani
  class Parser < Racc::Parser

module_eval(<<'...end lani.y/module_eval...', 'lani.y', 95)

def filename
  @filename
end

alias_method :parse_string, :scan_str

def pre_exe
  []
end

def on_error(t, val, vstack)
  raise ParseError, sprintf("\nparse error on value %s (%s) #{@filename}:#{@line}",
      val.inspect, token_to_str(t) || '?')
end

...end lani.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     4,     5,    35,    36,    37,    38,    42,    43,    15,     6,
     7,    23,     8,     9,    10,    11,     4,     5,    12,    30,
    46,    45,    25,    44,    15,     6,     7,    26,     8,     9,
    10,    11,     4,     5,    12,    35,    36,    37,    38,    39,
    15,     6,     7,   nil,     8,     9,    10,    11,    27,   nil,
    12,     4,     5,    35,    36,    37,    38,   nil,    47,    15,
     6,     7,   nil,     8,     9,    10,    11,     4,     5,    12,
    35,    36,    37,    38,   nil,    15,     6,     7,   nil,     8,
     9,    10,    11,     4,     5,    12,    35,    36,    37,    38,
   nil,    15,     6,     7,   nil,     8,     9,    10,    11,     4,
     5,    12,    35,    36,    37,    38,   nil,    15,     6,     7,
   nil,     8,     9,    10,    11,     4,     5,    12,    35,    36,
    37,    38,   nil,    15,     6,     7,   nil,     8,     9,    10,
    11,     4,     5,    12,    35,    36,    37,    38,   nil,    15,
     6,     7,   nil,     8,     9,    10,    11,     4,     5,    12,
    37,    38,    37,    38,   nil,    15,     6,     7,   nil,     8,
     9,    10,    11,     4,     5,    12,   nil,   nil,   nil,   nil,
   nil,    15,     6,     7,   nil,     8,     9,    10,    11,     4,
     5,    12,   nil,   nil,   nil,   nil,   nil,    15,     6,     7,
   nil,     8,     9,    10,    11,     4,     5,    12,   nil,   nil,
   nil,   nil,   nil,    15,     6,     7,   nil,     8,     9,    10,
    11,   nil,   nil,    12 ]

racc_action_check = [
    12,    12,    33,    33,    33,    33,    28,    28,    12,    12,
    12,     1,    12,    12,    12,    12,     0,     0,    12,    12,
    33,    31,     3,    31,     0,     0,     0,     7,     0,     0,
     0,     0,    11,    11,     0,    22,    22,    22,    22,    23,
    11,    11,    11,   nil,    11,    11,    11,    11,    11,   nil,
    11,    15,    15,    34,    34,    34,    34,   nil,    34,    15,
    15,    15,   nil,    15,    15,    15,    15,    24,    24,    15,
    29,    29,    29,    29,   nil,    24,    24,    24,   nil,    24,
    24,    24,    24,    26,    26,    24,    40,    40,    40,    40,
   nil,    26,    26,    26,   nil,    26,    26,    26,    26,    35,
    35,    26,    41,    41,    41,    41,   nil,    35,    35,    35,
   nil,    35,    35,    35,    35,    36,    36,    35,    52,    52,
    52,    52,   nil,    36,    36,    36,   nil,    36,    36,    36,
    36,    37,    37,    36,    54,    54,    54,    54,   nil,    37,
    37,    37,   nil,    37,    37,    37,    37,    38,    38,    37,
    48,    48,    49,    49,   nil,    38,    38,    38,   nil,    38,
    38,    38,    38,    43,    43,    38,   nil,   nil,   nil,   nil,
   nil,    43,    43,    43,   nil,    43,    43,    43,    43,    45,
    45,    43,   nil,   nil,   nil,   nil,   nil,    45,    45,    45,
   nil,    45,    45,    45,    45,    46,    46,    45,   nil,   nil,
   nil,   nil,   nil,    46,    46,    46,   nil,    46,    46,    46,
    46,   nil,   nil,    46 ]

racc_action_pointer = [
    14,    11,   nil,    14,   nil,   nil,   nil,    14,   nil,   nil,
   nil,    30,    -2,   nil,   nil,    49,   nil,   nil,   nil,   nil,
   nil,   nil,    31,    39,    65,   nil,    81,   nil,   -12,    66,
   nil,     2,   nil,    -2,    49,    97,   113,   129,   145,   nil,
    82,    98,   nil,   161,   nil,   177,   193,   nil,   144,   146,
   nil,   nil,   114,   nil,   130 ]

racc_action_default = [
    -2,   -37,    -1,    -3,    -4,    -5,    -6,    -7,    -9,   -10,
   -11,   -37,   -37,   -21,   -22,   -37,   -24,   -25,   -26,   -27,
   -28,   -29,   -34,   -37,   -37,   -36,   -37,   -12,   -37,   -14,
   -16,   -37,   -18,   -37,   -37,   -37,   -37,   -37,   -37,    55,
   -35,    -8,   -13,   -37,   -17,   -37,   -37,   -23,   -30,   -31,
   -32,   -33,   -15,   -19,   -20 ]

racc_goto_table = [
    22,    32,     1,     2,     3,    28,    31,    24,   nil,   nil,
   nil,    29,   nil,   nil,   nil,    34,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    40,   nil,    41,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    53,    48,    49,    50,    51,   nil,
   nil,   nil,   nil,    52,   nil,   nil,    54 ]

racc_goto_check = [
     8,    14,     1,     2,     3,    11,    13,    16,   nil,   nil,
   nil,     8,   nil,   nil,   nil,     8,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     8,   nil,     8,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    14,     8,     8,     8,     8,   nil,
   nil,   nil,   nil,     8,   nil,   nil,     8 ]

racc_goto_pointer = [
   nil,     2,     3,     4,   nil,   nil,   nil,   nil,     0,   nil,
   nil,    -6,   nil,    -6,   -11,   nil,     4 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,    13,    16,    17,    18,    33,    19,
    20,   nil,    21,   nil,   nil,    14,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 24, :_reduce_none,
  0, 25, :_reduce_2,
  1, 25, :_reduce_3,
  1, 27, :_reduce_4,
  1, 27, :_reduce_5,
  1, 28, :_reduce_6,
  1, 29, :_reduce_7,
  3, 30, :_reduce_8,
  1, 32, :_reduce_9,
  1, 32, :_reduce_10,
  1, 32, :_reduce_11,
  2, 33, :_reduce_12,
  3, 33, :_reduce_13,
  1, 34, :_reduce_14,
  3, 34, :_reduce_15,
  2, 35, :_reduce_16,
  3, 35, :_reduce_17,
  1, 36, :_reduce_18,
  3, 36, :_reduce_19,
  3, 37, :_reduce_20,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  3, 31, :_reduce_23,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  3, 38, :_reduce_30,
  3, 38, :_reduce_31,
  3, 38, :_reduce_32,
  3, 38, :_reduce_33,
  1, 26, :_reduce_34,
  3, 26, :_reduce_35,
  1, 39, :_reduce_none ]

racc_reduce_n = 37

racc_shift_n = 55

racc_token_table = {
  false => 0,
  :error => 1,
  :INTEGER => 2,
  :FLOAT => 3,
  :ADD => 4,
  :SUBTRACT => 5,
  :MULTIPLY => 6,
  :DIVIDE => 7,
  :NEWLINE => 8,
  :RPAREN => 9,
  :LPAREN => 10,
  :STRING => 11,
  :IDENTIFIER => 12,
  :ASSIGN => 13,
  :TRUE => 14,
  :FALSE => 15,
  :NIL => 16,
  :LSQBRA => 17,
  :RSQBRA => 18,
  :COMMA => 19,
  :LCBRA => 20,
  :RCBRA => 21,
  :ROCKET => 22 }

racc_nt_base = 23

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "INTEGER",
  "FLOAT",
  "ADD",
  "SUBTRACT",
  "MULTIPLY",
  "DIVIDE",
  "NEWLINE",
  "RPAREN",
  "LPAREN",
  "STRING",
  "IDENTIFIER",
  "ASSIGN",
  "TRUE",
  "FALSE",
  "NIL",
  "LSQBRA",
  "RSQBRA",
  "COMMA",
  "LCBRA",
  "RCBRA",
  "ROCKET",
  "$start",
  "root",
  "program",
  "expressions",
  "number",
  "string",
  "variable_access",
  "variable_assignment",
  "expression",
  "boolean",
  "array",
  "elements",
  "hash",
  "pairs",
  "pair",
  "binary_operation",
  "terminator" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'lani.y', 34)
  def _reduce_2(val, _values)
     AST::Program.new( filename, lineno, [])
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 35)
  def _reduce_3(val, _values)
     AST::Program.new( filename, lineno, val[0])
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 37)
  def _reduce_4(val, _values)
     AST::IntegerNode.new( filename, lineno, val[0])
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 38)
  def _reduce_5(val, _values)
     AST::FloatNode.new( filename, lineno, val[0])
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 40)
  def _reduce_6(val, _values)
     AST::StringNode.new( filename, lineno, val[0])
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 42)
  def _reduce_7(val, _values)
     AST::VariableAccessNode.new( filename, lineno, val[0])
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 44)
  def _reduce_8(val, _values)
     AST::VariableAssignmentNode.new( filename, lineno, val[0], val[2]) 
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 46)
  def _reduce_9(val, _values)
     AST::TrueBooleanNode.new( filename, lineno)
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 47)
  def _reduce_10(val, _values)
     AST::FalseBooleanNode.new( filename, lineno)
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 48)
  def _reduce_11(val, _values)
     AST::NilBooleanNode.new( filename, lineno)
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 50)
  def _reduce_12(val, _values)
     AST::ArrayNode.new( filename, lineno, [])
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 51)
  def _reduce_13(val, _values)
     AST::ArrayNode.new( filename, lineno, val[1])
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 53)
  def _reduce_14(val, _values)
     [val[0]] 
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 54)
  def _reduce_15(val, _values)
     val[0] << val[2] 
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 56)
  def _reduce_16(val, _values)
     AST::HashNode.new( filename, lineno, [])
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 57)
  def _reduce_17(val, _values)
     AST::HashNode.new( filename, lineno, val[1])
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 59)
  def _reduce_18(val, _values)
     [val[0]] 
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 60)
  def _reduce_19(val, _values)
     val[0] << val[2] 
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 62)
  def _reduce_20(val, _values)
     [val[0], val[2]]
  end
.,.,

# reduce 21 omitted

# reduce 22 omitted

module_eval(<<'.,.,', 'lani.y', 68)
  def _reduce_23(val, _values)
     val[1] 
  end
.,.,

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

module_eval(<<'.,.,', 'lani.y', 77)
  def _reduce_30(val, _values)
    AST::AddNode.new( filename, lineno, val[0], val[2])
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 78)
  def _reduce_31(val, _values)
    AST::SubtractNode.new( filename, lineno, val[0], val[2])
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 79)
  def _reduce_32(val, _values)
    AST::MultiplyNode.new( filename, lineno, val[0], val[2])
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 80)
  def _reduce_33(val, _values)
    AST::DivideNode.new( filename, lineno, val[0], val[2])
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 82)
  def _reduce_34(val, _values)
     [val[0]] 
  end
.,.,

module_eval(<<'.,.,', 'lani.y', 83)
  def _reduce_35(val, _values)
     val[0] << val[2] 
  end
.,.,

# reduce 36 omitted

def _reduce_none(val, _values)
  val[0]
end

  end   # class Parser
  end   # module Lani


